# Generated by Django 4.1 on 2023-04-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesor",
            name="matricula",
            field=models.IntegerField(),
        ),
    ]
